#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# disable beep
xset b off

# set screensaver and dpms to 20min
xset s 1200 1200
xset dpms 1200 1200 1200

# update font config
xset +fp /usr/share/fonts/local
xset fp rehash

# load .Xresources and .Xdefaults
xrdb -merge ~/.Xresources
xrdb -merge ~/.Xdefaults

# init keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

# override style for QT applications
export QT_STYLE_OVERRIDE=gtk

# fix trackpoint issues
sudo ~/.local/bin/fixtp &

# set dircolors
eval $(dircolors -b ~/.dircolors)

# launch compositor
compton -CGb -f -D 5 --backend glx

for i in {1..3}; do
  xrandr -q | grep "DP${i} connected" && xrandr --output LVDS1 --off --output DP${i} --auto --primary
  xrandr -q | grep "HDMI${i} connected" && xrandr --output LVDS1 --off --output HDMI${i} --auto --primary
done

exec i3
