#!/usr/bin/python3

import json
import requests
import sys
import webbrowser

# openweathermap api key
APPID = "8ab59c0c302e4fafaca328679cc81188"

# city for which to look up the weather
CITY = "Berlin,DE"

# http request timeout
TIMEOUT = 5

def get_weather():
  url = "https://api.openweathermap.org/data/2.5/weather" \
        "?units=metric&q=%s&appid=%s" % (CITY, APPID)

  try:
    r = requests.get(url, timeout=TIMEOUT)
    if r.status_code == 200:
      return r.json()
  except Exception:
    pass

  return None

def print_weather(weather):
  if weather and weather['cod'] == 200:
    try:
      temp = int(weather['main']['temp'])
    except KeyError:
      temp = 'n/a'
    status = int(weather['weather'][0]['id'])

    if 200 <= status < 300:
      cond = 'thunderstorm'
    elif 300 <= status < 400:
      cond = 'drizzle'
    elif 500 <= status < 600:
      cond = 'rain'
    elif 600 <= status < 700:
      cond = 'snow'
    elif status == 800:
      cond = 'clear sky'
    elif 800 < status < 900:
      cond = 'clouds'
    else:
      cond = weather['weather'][0]['description']

    print("%s°C, %s" % (temp, cond))
  else:
    sys.exit("unknown")

def open_browser(weather):
  url = 'https://openweathermap.org/city/'

  if weather and weather['cod'] == 200:
    url += str(weather['id'])

  webbrowser.open(url)

if __name__ == '__main__':
  weather = get_weather()

  if len(sys.argv) > 1 and sys.argv[1] == 'browser':
    open_browser(weather)
  else:
    print_weather(weather)
