format = """
$directory\
$git_branch\
$git_commit\
${custom.git_tag}\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$jobs\
$character"""

[aws]
symbol = " "

[cmd_duration]
format = "[{$duration}]($style) "
min_time = 5000
show_milliseconds = true
style = "fg:black"

[directory]
truncate_to_repo = false
truncation_length = 4
read_only = " "
read_only_style = "fg:red"
style = "fg:blue"

[docker_context]
symbol = " "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "red"
only_attached = true

[git_commit]
only_detached = true
tag_disabled = true
format = "[ $hash]($style) "
style = "fg:red"

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
added_style = "fg:#009900"
deleted_style = "fg:#990000"

[git_status]
format = '([$ahead_behind](fg:cyan) )([$all_status]($style) )'
modified = ""
stashed = ""
untracked = ""
style = "fg:yellow"

[golang]
symbol = " "

[java]
symbol = " "

[jobs]
format = "[$number]($style) "
number_threshold = 1
style = "green"

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[shlvl]
symbol = " "

[custom.git_tag]
description = "Shows the git tag, if the current commit points to one"
command = "git describe --tags --exact-match"
shell = ["bash","--norc","--noprofile"]
when = "git rev-parse --git-dir"
format = "([$output]($style) )"
style = "fg:#ddcc00"
