#!/bin/bash

# prevent curl from hanging by limiting request time to 5sec
ip=$(curl -s --max-time 5 https://api.ipify.org/)

if [ $? -eq 0 ]; then
  echo "online $ip"
else
  echo "offline"
  exit 1
fi
