#!/bin/bash

cd /etc/openvpn

for f in *.conf; do
  profile=${f%.*}
  output=$(systemctl show openvpn@$profile | grep -oP 'ActiveState=\K(\w+)')

  if [ "$output" = "active" ]; then
    echo "vpn on"
    exit 0
  fi
done

# no vpn active, exit with error code
echo "vpn off"
exit 1
