#!/bin/bash

[ $# -lt 1 ] && { echo "n/a"; exit 1; } 

output=$(systemctl show openvpn@$1 | grep -oP 'ActiveState=\K(\w+)')

if [ "$output" = "active" ]; then
  echo "vpn on"
else
  echo "vpn off"
  exit 1
fi
